version: '3'
services:
  app:
    build: .
    environment:
      CQLENG_ALLOW_SCHEMA_MANAGEMENT: True
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
  cassandra:
    image: cassandra:3.11
    ports:
      - 9042:9042
  redis:
    image: redis
    ports:
      - 6379:6379
    command: >
      sh -c "redis-server
      && redis-cli CONFIG SET maxmemory 4gb

